### PR TITLE
Don't display disabled actions

### LINKED ISSUE #5: Display of not enabled state actions
In Hollow Knight 1.5.78.numbers, in
"Fungus2_01" (level165) -> "Quirrel Station NPC" gameobject -> "Conversation Control" FSM -> "Convo Choice" state the first of 3 displayed actions is a `BoolTest`, but looking at the FSM in AssetsView, i can see that, in the `actionEnabled` array of that state, the action is disabled.

### PR DESCRIPTION
**Pull request by SFGrenade**
Fixes #5

### CODE REVIEW

**Comment by flibber-hk** [comment]
Do you think it'd be better to display the action, but indicate it's disabled somehow? Maybe cut the opacity or something?

**Comment by SFGrenade** [comment]
oh true, maybe it is better with an indication, as hk mods sometimes change fsm actions and the disabled actions could be in the way of what is wanted.

**Comment by nesrak1** [comment]
Do you want to add an indicator then, or should I just pull this?

**Comment by SFGrenade** [comment]
i'll try to make an indicator, can utilize that single `if`.

**Comment by SFGrenade** [comment]
not a designer, would something like this look good?
grafik

**Comment by flibber-hk** [comment]
Second one looks good to me

**Comment by SFGrenade** [comment]
second one is the commit

**Pull request merged**
